// Module: Top-Level CPU - Integration & Control
// Supports instructions: add, sub, and, or, mov, loadi
// This module integrates all components into a top-level datapath

module cpu(PC, INSTRUCTION, CLK, RESET);

    // Port Declarations
    output wire [31:0] PC;       // Program Counter (driven by pc_unit)
    input [31:0] INSTRUCTION;   // 32-bit instruction fetched from instruction memory
    input CLK;                  // Clock signal
    input RESET;                // Reset signal (synchronous)

    // Control Signals (generated by control_unit)
    wire [2:0] READREG1;        // Address for read port 1 of register file
    wire [2:0] READREG2;        // Address for read port 2 of register file
    wire [2:0] WRITEREG;        // Address for write port of register file
    wire WRITEENABLE;           // Write enable signal for register file
    wire [2:0] ALUOP;           // ALU operation select
    wire MUX_IMM_SEL;           // MUX select: 0 = register value, 1 = immediate value
    wire MUX_COMP_SEL;          // MUX select: 0 = original value, 1 = 2's complement
    wire [7:0] IMMEDIATE;       // Immediate value extracted from instruction

    // Internal Wires for Data Routing
    wire [7:0] REGOUT1;        // Output from register file port 1 (RT value)
    wire [7:0] REGOUT2;        // Output from register file port 2 (RS value)
    wire [7:0] ALURESULT;      // Result from ALU
    wire [7:0] TWOS_COMP_OUT;  // 2's complement of REGOUT2 (for SUB)
    wire [7:0] MUX_COMP_RESULT;// Output of 2's complement MUX
    wire [7:0] MUX_IMM_RESULT; // Output of immediate MUX

    // ============================================================
    // PC Unit Instantiation
    // ============================================================
    pc_unit mypc(
        .PC(PC),
        .CLK(CLK),
        .RESET(RESET)
    );

    // ============================================================
    // Control Unit Instantiation
    // ============================================================
    control_unit mycontrol(
        .INSTRUCTION(INSTRUCTION),
        .READREG1(READREG1),
        .READREG2(READREG2),
        .WRITEREG(WRITEREG),
        .WRITEENABLE(WRITEENABLE),
        .ALUOP(ALUOP),
        .MUX_IMM_SEL(MUX_IMM_SEL),
        .MUX_COMP_SEL(MUX_COMP_SEL),
        .IMMEDIATE(IMMEDIATE)
    );

    // ============================================================
    // 2's Complement Unit Instantiation
    // ============================================================
    twos_complement mytwoscomp(
        .IN(REGOUT2),
        .OUT(TWOS_COMP_OUT)
    );

    // ============================================================
    // MUX: 2's Complement Select
    // ============================================================
    mux_2x1_8bit mux_comp(
        .IN0(REGOUT2),
        .IN1(TWOS_COMP_OUT),
        .SEL(MUX_COMP_SEL),
        .OUT(MUX_COMP_RESULT)
    );

    // ============================================================
    // MUX: Immediate Value Select
    // ============================================================
    mux_2x1_8bit mux_imm(
        .IN0(MUX_COMP_RESULT),
        .IN1(IMMEDIATE),
        .SEL(MUX_IMM_SEL),
        .OUT(MUX_IMM_RESULT)
    );

    // ============================================================
    // ALU Instantiation
    // ============================================================
    alu myalu(
        .DATA1(REGOUT1),
        .DATA2(MUX_IMM_RESULT),
        .RESULT(ALURESULT),
        .SELECT(ALUOP)
    );

    // ============================================================
    // Register File Instantiation
    // ============================================================
    reg_file myreg(
        .IN(ALURESULT),
        .OUT1(REGOUT1),
        .OUT2(REGOUT2),
        .INADDRESS(WRITEREG),
        .OUT1ADDRESS(READREG1),
        .OUT2ADDRESS(READREG2),
        .WRITE(WRITEENABLE),
        .CLK(CLK),
        .RESET(RESET)
    );

endmodule
