
// Module: Top-Level CPU - Integration & Control
// Supports instructions: add, sub, and, or, mov, loadi
// This module integrates the ALU and Register File with control logic


// OP-CODE Assignments 
//   8'b00000000 (0x00) = loadi  -> load immediate to RD
//   8'b00000001 (0x01) = mov    -> copy RT to RD
//   8'b00000010 (0x02) = add    -> RD = RT + RS
//   8'b00000011 (0x03) = sub    -> RD = RT - RS
//   8'b00000100 (0x04) = and    -> RD = RT & RS
//   8'b00000101 (0x05) = or     -> RD = RT | RS

// Timing Delays:
//   PC Update             = #1 time unit
//   Instruction Mem Read  = #2 time units  (handled in testbench)
//   PC+4 Adder            = #1 time unit   (parallel with instr mem read)
//   Instruction Decode    = #1 time unit
//   2's Complement        = #1 time unit   (only for sub)
//   Register Read         = #2 time units  (built into reg_file)
//   ALU                   = #1 or #2 time units (built into ALU functional units)
//   Register Write        = #1 time unit   (built into reg_file on posedge CLK)


module cpu(PC, INSTRUCTION, CLK, RESET);

    // Port Declarations

    output reg [31:0] PC;       // Program Counter (output to testbench for instruction fetch)
    input [31:0] INSTRUCTION;   // 32-bit instruction fetched from instruction memory
    input CLK;                  // Clock signal
    input RESET;                // Reset signal (synchronous)


    // Instruction Decode Wires

    // Extract fields from the 32-bit instruction
    wire [7:0] OPCODE;         // Bits [31:24] - Operation code
    wire [7:0] RD_IMM;         // Bits [23:16] - Destination register or immediate (for j/beq)
    wire [7:0] RT;             // Bits [15:8]  - Source register 1
    wire [7:0] RS_IMM;         // Bits [7:0]   - Source register 2 or immediate

    assign OPCODE  = INSTRUCTION[31:24];
    assign RD_IMM  = INSTRUCTION[23:16];
    assign RT      = INSTRUCTION[15:8];
    assign RS_IMM  = INSTRUCTION[7:0];


    // Control Signals (generated by decode logic)

    reg [2:0] READREG1;        // Address for read port 1 of register file
    reg [2:0] READREG2;        // Address for read port 2 of register file
    reg [2:0] WRITEREG;        // Address for write port of register file
    reg WRITEENABLE;           // Write enable signal for register file
    reg [2:0] ALUOP;           // ALU operation select
    reg MUX_IMM_SEL;           // MUX select: 0 = register value, 1 = immediate value
    reg MUX_COMP_SEL;          // MUX select: 0 = original value, 1 = 2's complement
    reg [7:0] IMMEDIATE;       // Immediate value extracted from instruction


    // Internal Wires

    wire [7:0] REGOUT1;        // Output from register file port 1 (RT value)
    wire [7:0] REGOUT2;        // Output from register file port 2 (RS value)
    wire [7:0] ALURESULT;      // Result from ALU
    
    reg [7:0] TWOS_COMP_OUT;   // 2's complement of REGOUT2 (for SUB)
    reg [7:0] MUX_COMP_RESULT; // Output of 2's complement MUX
    reg [7:0] MUX_IMM_RESULT;  // Output of immediate MUX (selects between reg value and immediate)
    
    wire [31:0] PC_NEXT;       // Next PC value (PC + 4)


    // PC + 4 Adder

    // Dedicated adder to increment PC by 4 (one instruction = 4 bytes)
    // Latency: #1 time unit, works in parallel with instruction memory read
    assign #1 PC_NEXT = PC + 32'd4;


    // PC Update Logic (Synchronous, on positive clock edge)

    // If RESET is high, PC is set to 0 (restart program)
    // Otherwise, PC is updated to PC + 4
    // Delay: #1 time unit for PC write
    always @(posedge CLK) begin
        if (RESET) begin
            #1 PC = 32'd0;         // Reset PC to address 0
        end else begin
            #1 PC = PC_NEXT;       // Advance to next instruction
        end
    end


    // Instruction Decode & Control Signal Generation

    // Combinational logic that decodes the fetched instruction and generates
    // all control signals. This happens after instruction memory read completes.
    // Decode delay: #1 time unit
    always @(INSTRUCTION) begin
        #1;  // Instruction decode delay
        
        // Default values for control signals
        WRITEENABLE = 1'b0;
        MUX_IMM_SEL = 1'b0;
        MUX_COMP_SEL = 1'b0;
        ALUOP = 3'b000;
        IMMEDIATE = RS_IMM;
        
        // Extract register addresses from instruction fields
        // Only lower 3 bits are used since we have 8 registers (0-7)
        WRITEREG = RD_IMM[2:0];   // Destination register
        READREG1 = RT[2:0];        // Source register 1
        READREG2 = RS_IMM[2:0];    // Source register 2
        
        case (OPCODE)
            // -------------------------------------------------------
            // LOADI: Load immediate value to register RD
            // RD = IMMEDIATE (bits 7-0)
            // ALU FORWARD (SELECT=000) passes the immediate value
            // MUX_IMM_SEL = 1 to select immediate instead of register
            // -------------------------------------------------------
            8'b00000000: begin
                ALUOP = 3'b000;         // FORWARD operation
                MUX_IMM_SEL = 1'b1;     // Select immediate value
                MUX_COMP_SEL = 1'b0;    // No 2's complement needed
                WRITEENABLE = 1'b1;      // Enable register write
                IMMEDIATE = RS_IMM;      // Immediate value from bits [7:0]
            end
            
            // -------------------------------------------------------
            // MOV: Copy value from register RT to register RD
            // RD = RT
            // ALU FORWARD (SELECT=000) passes REGOUT1 (value of RT)
            // We read from RT via READREG2 and forward it
            // -------------------------------------------------------
            8'b00000001: begin
                ALUOP = 3'b000;         // FORWARD operation
                MUX_IMM_SEL = 1'b0;     // Select register value (not immediate)
                MUX_COMP_SEL = 1'b0;    // No 2's complement needed
                WRITEENABLE = 1'b1;      // Enable register write
                READREG2 = RT[2:0];      // Read the source register (RT)
            end
            
            // -------------------------------------------------------
            // ADD: RD = RT + RS
            // ALU ADD (SELECT=001) computes REGOUT1 + REGOUT2
            // -------------------------------------------------------
            8'b00000010: begin
                ALUOP = 3'b001;         // ADD operation
                MUX_IMM_SEL = 1'b0;     // Select register value
                MUX_COMP_SEL = 1'b0;    // No 2's complement (positive operand)
                WRITEENABLE = 1'b1;      // Enable register write
            end
            
            // -------------------------------------------------------
            // SUB: RD = RT - RS
            // Uses ADD with 2's complement of RS: RT + (~RS + 1)
            // MUX_COMP_SEL = 1 to select 2's complement of REGOUT2
            // -------------------------------------------------------
            8'b00000011: begin
                ALUOP = 3'b001;         // ADD operation (add with 2's complement)
                MUX_IMM_SEL = 1'b0;     // Select register value
                MUX_COMP_SEL = 1'b1;    // Select 2's complement of RS
                WRITEENABLE = 1'b1;      // Enable register write
            end
            
            // -------------------------------------------------------
            // AND: RD = RT & RS (bitwise AND)
            // ALU AND (SELECT=010)
            // -------------------------------------------------------
            8'b00000100: begin
                ALUOP = 3'b010;         // AND operation
                MUX_IMM_SEL = 1'b0;     // Select register value
                MUX_COMP_SEL = 1'b0;    // No 2's complement needed
                WRITEENABLE = 1'b1;      // Enable register write
            end
            
            // -------------------------------------------------------
            // OR: RD = RT | RS (bitwise OR)
            // ALU OR (SELECT=011)
            // -------------------------------------------------------
            8'b00000101: begin
                ALUOP = 3'b011;         // OR operation
                MUX_IMM_SEL = 1'b0;     // Select register value
                MUX_COMP_SEL = 1'b0;    // No 2's complement needed
                WRITEENABLE = 1'b1;      // Enable register write
            end
            
            // -------------------------------------------------------
            // Default: Unknown opcode, disable all writes
            // -------------------------------------------------------
            default: begin
                WRITEENABLE = 1'b0;
            end
        endcase
    end

    // ============================================================
    // 2's Complement Unit
    // ============================================================
    // Computes the 2's complement (~value + 1) of REGOUT2
    // Used for SUB instruction: RT - RS = RT + (~RS + 1)
    // Latency: #1 time unit
    always @(REGOUT2) begin
        #1 TWOS_COMP_OUT = ~REGOUT2 + 8'd1;
    end

    // ============================================================
    // MUX: 2's Complement Select
    // ============================================================
    // Selects between original REGOUT2 and its 2's complement
    //   MUX_COMP_SEL = 0: pass REGOUT2 (for add, and, or, etc.)
    //   MUX_COMP_SEL = 1: pass 2's complement of REGOUT2 (for sub)
    // Assumption: MUX has negligible delay
    always @(*) begin
        case (MUX_COMP_SEL)
            1'b0: MUX_COMP_RESULT = REGOUT2;
            1'b1: MUX_COMP_RESULT = TWOS_COMP_OUT;
        endcase
    end

    // ============================================================
    // MUX: Immediate Value Select
    // ============================================================
    // Selects between the MUX_COMP_RESULT (register/2's comp value) 
    // and the IMMEDIATE value
    //   MUX_IMM_SEL = 0: pass MUX_COMP_RESULT (register path)
    //   MUX_IMM_SEL = 1: pass IMMEDIATE value (for loadi)
    // Assumption: MUX has negligible delay
    always @(*) begin
        case (MUX_IMM_SEL)
            1'b0: MUX_IMM_RESULT = MUX_COMP_RESULT;
            1'b1: MUX_IMM_RESULT = IMMEDIATE;
        endcase
    end

    // ============================================================
    // ALU Instantiation
    // ============================================================
    // DATA1 = REGOUT1 (value from register RT - first source operand)
    // DATA2 = MUX_IMM_RESULT (either register value, 2's comp, or immediate)
    // RESULT = ALURESULT (written back to register file)
    // SELECT = ALUOP (operation select from control unit)
    alu myalu(
        .DATA1(REGOUT1),
        .DATA2(MUX_IMM_RESULT),
        .RESULT(ALURESULT),
        .SELECT(ALUOP)
    );

    // ============================================================
    // Register File Instantiation
    // ============================================================
    // IN = ALURESULT (data to write comes from ALU output)
    // OUT1 = REGOUT1 (connected to ALU DATA1 - value of RT)
    // OUT2 = REGOUT2 (connected to 2's complement MUX - value of RS)
    // INADDRESS = WRITEREG (destination register from instruction)
    // OUT1ADDRESS = READREG1 (RT register address)
    // OUT2ADDRESS = READREG2 (RS register address)
    // WRITE = WRITEENABLE (from control logic)
    // CLK and RESET are passed through from CPU ports
    reg_file myreg(
        .IN(ALURESULT),
        .OUT1(REGOUT1),
        .OUT2(REGOUT2),
        .INADDRESS(WRITEREG),
        .OUT1ADDRESS(READREG1),
        .OUT2ADDRESS(READREG2),
        .WRITE(WRITEENABLE),
        .CLK(CLK),
        .RESET(RESET)
    );

endmodule
